### PR TITLE
New package size cost

### PR DESCRIPTION
**Pull request by Zinat02**

### CODE REVIEW

**Comment by bitNathan** [comment]
Just merged some things to allow for testing, none of the actual functionality's been changed

Just a quick fyi if anyone's looking at it

**Comment by bitNathan** [comment]
indexing had to change to unpack the sql response, so that's why the tests are now failing

Error handling seems good, but actually calculating results gets this
  Error rating package: Error failed to get a response from the API
Looking into causes

**Comment by bitNathan** [comment]
update on the issue above, problem is with phase 1 code, took awhile to find because their logger didn't work right

**Review by bitNathan — APPROVED** [review]
minor updates and rate looks good

costs references a column in the sql table we don't currently have though

**Review by MadSons — COMMENTED** [review]
The component for .tsx should make a call to services/api.ts in order to do the GET or POST call to the backend. These GET and POST calls should also be done with axios, not a simple fetch. I was getting frontend error trying to call the backend with the method you had before. The downloadPackage method in the frontend does a GET request you may mimic to call the backend. @Zinat02

**Pull request merged**
